version: "3.7"
services:
  restshaper_api:
    build:
      context: .
      dockerfile: Api.Dockerfile
    volumes:
      - ./target:/target
    environment:
      - IS_DOCKER=true
    ports:
      - "8001:8001"

networks:
  default:
    name: restshaper-network